### ISSUE TITLE
../sys/sdl12/init.h:29:10: fatal error: SDL.h: No such file or directory

### ISSUE THREAD

**Issue by squeaktoy** [schismtracker/schismtracker#803]
# Description
Schism Tracker cannot be built on Gentoo due to problems including SDL.h.

# Steps to reproduce
```
git clone https://github.com/schismtracker/schismtracker
cd schismtracker
mkdir build
autoreconf -i
cd build
../configure
make
```

# Expected result
schismtracker binary successfully built

# Actual result
```
gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I.    -O -D_FORTIFY_SOURCE=2    -Isys/x11        -D_REENTRANT     -DUTF8PROC_EXPORTS    -g -O2 -Werror=return-type -Werror=implicit-int -Werror=implicit-function-declaration -Werror=old-style-declaration -Werror=old-style-definition -Werror=write-strings -Werror=restrict -Werror=overlength-strings     -I/usr/local/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -MT sys/sdl12/schismtracker-audio.o -MD -MP -MF sys/sdl12/.deps/schismtracker-audio.Tpo -c -o sys/sdl12/schismtracker-audio.o `test -f 'sys/sdl12/audio.c' || echo '../'`sys/sdl12/audio.c
In file included from ../sys/sdl12/audio.c:30:
../sys/sdl12/init.h:29:10: fatal error: SDL.h: No such file or directory
   29 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
make[1]: *** [Makefile:4893: sys/sdl12/schismtracker-audio.o] Error 1
make[1]: Leaving directory '/home/user/software/media-sound/schismtracker/build'
make: *** [Makefile:1489: all] Error 2
```

# System info
OS: Gentoo Linux
Compiler: gcc version 15.2.1 20251122 (Gentoo 15.2.1_p20251122 p4) 
SDL version: =media-libs/libsdl2-2.32.8 =media-libs/libsdl3-3.2.26

**Comment by mrpapersonic** [comment]
Well, it's trying to build with SDL 1.2 support enabled, which probably isn't what you want. You can force disable it with `--without-sdl12`.

> `-I/usr/local/include/SDL`

Did you happen to build a custom SDL 1.2 and then delete it from your system? In that case this would make sense, and you just have a broken environment. Make sure that `/usr/local/lib/pkgconfig/sdl.pc` doesn't exist.

**Comment by squeaktoy** [comment]
It turns out that there was some sdl m4 crap and sdl-config lingering in /usr/local.
After deleting that, Schism Tracker now builds successfully.
