### ISSUE TITLE
Schismtracker uses C99 features without specifying -std=[...] on the command line

### ISSUE THREAD

**Issue by alarixnia** [schismtracker/schismtracker#624]
When compiling with GCC 4.x, the following errors appear:

~~~
fmt/compression.c: In function 'mdl_decompress8':
fmt/compression.c:301:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (uint32_t j=0; j<len; j++) {
  ^
fmt/compression.c:301:2: note: use option -std=c99 or -std=gnu99 to compile your code
fmt/compression.c: In function 'mdl_decompress16':
fmt/compression.c:349:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (uint32_t j=0; j<len; j++) {
  ^
~~~

The compiler supports C99, but schismtracker does not specify that it is using C99.

**Comment by mrpapersonic** [comment]
Are you using the tarball or generating configure yourself? If the latter your autoconf is probably too old to support the new AC_PROG_CC behavior that schism depends on

Also, configure should emit a warning if C99 support couldn't be found (see config.log)

**Comment by mrpapersonic** [comment]
okay, this should be fixed as of a000816; we get a deprecation warning with newer autoconf but at least it seems to work with 2.69 now
